### ISSUE TITLE
Inventory duplicate

### ISSUE THREAD

**Issue by Henry5K** [nhanaz-pm-pl/KeepInventory#8] opened 2022-08-24 09:40 UTC
When you death, your Inventory duplicate, a half to victim and a half to assassin
My config:
```yaml
---
# KeepInventory Mode
#  true : Prevents players from losing items on death
#  false : Players from losing items on death
KeepInventory: true

# all : All worlds will be affected by KeepInventory Mode
# whitelist : All worlds listed below will be affected by KeepInventory Mode
# blacklist : All worlds not listed below will be affected by KeepInventory Mode
Mode: all
Worlds: []
# Worlds: ["Plots", "Arena"]

# Message to players if their inventory is safe
MsgAfterDeathTrue: "You died, but your inventory is safe!"

# Message to players if their inventory is not safe
MsgAfterDeathFalse: "You died and your inventory is not safe!"

# none : No messages have been sent to the player
# message : Sends a direct chat message to a player
# title : Send a title text to the user's screen
# popup : Sends a popup message to the player
# tip : Sends a tip message to the player
# actionbar : Send a small text to the user's screen
# MsgType: none
...
```

**Comment by NhanAZ** [comment] 2022-08-24 09:52
Could you tell me which version you're using?
`/version KeepInventory` to see the version

**Comment by Henry12960** [comment] 2022-08-24 14:53
> Could you tell me which version you're using? `/version KeepInventory` to see the version

**2.1.3**

**Comment by NhanAZ** [comment] 2022-08-24 19:13
Does this happen when you remove all plugins and install only KeepInventory plugin?

**Comment by NhanAZ** [comment] 2022-08-24 19:14
I guess some stupid plugin in your server caused this bug.

**Comment by NhanAZ** [comment] 2022-08-24 19:14
I tried to reproduce the bug but the bug does not appear. The plugin works pretty well for me.

**Comment by Henry12960** [comment] 2022-08-24 21:33
I remove all plugins and continue... I'll try to record

**Comment by PetterLight** [comment] 2022-08-29 00:37
I can confirm this

**Comment by NhanAZ** [comment] 2022-08-29 07:20
Fixed by https://github.com/nhanaz-pm-pl/KeepInventory/commit/ec115877db5dae7528532f168aa925d000cd6d38

**Comment by NhanAZ** [comment] 2022-08-29 07:31
Download the latest version at: https://poggit.pmmp.io/p/KeepInventory/2.1.4

**Comment by Henry12960** [comment] 2022-08-29 11:36
> Corrigido por [ec11587](https://github.com/nhanaz-pm-pl/KeepInventory/commit/ec115877db5dae7528532f168aa925d000cd6d38)

...

**Comment by Henry12960** [comment] 2022-08-29 11:37
Bruh, autocheck updater fixed this '-'

**Comment by NhanAZ** [comment] 2023-05-20 12:14
@Henry5K @NotViper
I'm not sure what's going on. It seems that the plugin is conflicting with something on your server and the plugin works fine on mine. I think this error occurs due to the priority of the events so I edited the plugin's event handling priority.
Please try v3.0.0 https://poggit.pmmp.io/p/KeepInventory/3.0.0

**Comment by Henry8K** [comment] 2023-05-20 12:15
I will look for the solution for this

**Comment by Henry8K** [comment] 2023-05-20 12:15
keep doubling

**Comment by NhanAZ** [comment] 2023-05-20 12:16
Did you delete the old configuration?

**Comment by Henry8K** [comment] 2023-05-20 12:18
Yeah

**Comment by NhanAZ** [comment] 2023-05-20 12:19
Can you show the plugin list?

**Comment by NhanAZ** [comment] 2023-05-20 12:23
If possible a video that reproduces the error...

**Comment by Henry8K** [comment] 2023-05-20 12:30
MultiWorld
BuilderTools
KeepInventory
KeepEXP

**Comment by Henry8K** [comment] 2023-05-20 12:30
> If possible a video that reproduces the error...

Ok

**Comment by NhanAZ** [comment] 2023-05-20 12:42
> KeepEXP

i tried to reproduce the error on my server with this plugin list but the error did not occur :(

```
Plugins (14): BlockDataRecorder v0.0.4, BlockData_Example_Plugin v0.0.1, BuilderTools v1.4.0, DEVirion v1.2.8, DevTools v1.16.1, KeepExp v0.0.1, KeepInventory v3.0.0, LockedItem v5.0.0, MultiWorld v2.0.0-beta1, NPC v0.0.1, NpcDialogue v0.0.1, TerrainGenerator v0.0.1, Test v0.0.1, pmforms-demo v0.0.1
```

maybe waiting for someone's PR

**Comment by Henry8K** [comment] 2023-05-21 17:41
The exact error occurs when the player kills another player and they have the same item in their inventory, like a sword, I tried to record, but my cell phone does not support it, and I do not have minecraft bedrock on my computer, F

**Comment by NhanAZ** [comment] 2023-05-23 03:45
![image](https://github.com/nhanaz-pm-pl/KeepInventory/assets/60387689/8ad56346-eb7b-42da-9ca5-1798b3358679)

can you show plugin list? if possible please provide a video that reproduces the error.

**Comment by NhanAZ** [comment] 2023-05-23 11:34
@SillierShark195 https://youtu.be/rb_TbiV_VrA

Does the error occur when you delete the KeepInventory plugin?

**Comment by SillierShark195** [comment] 2023-05-23 11:52
> @SillierShark195 https://youtu.be/rb_TbiV_VrA
> 
> Does the error occur when you delete the KeepInventory plugin?

All back to normal when IM remove it

**Comment by NhanAZ** [comment] 2023-06-18 12:37
This bug was fixed by https://github.com/nhanaz-pm-pl/KeepInventory/compare/bad2f05e8667...fa148b861ddf

This error occurs due to conflicts with some plugins such as:
- https://poggit.pmmp.io/p/AutoInventory
- https://poggit.pmmp.io/p/AutoPickup

To fix this error please remove the conflicting plugin or update KeepInventory to version 3.1.1 or later if available.

Download the latest version at: https://poggit.pmmp.io/p/KeepInventory/3.0.1 (Not approved at the time this comment was posted, please wait)

Latest version download link for posterity: https://poggit.pmmp.io/p/KeepInventory

**Closed by NhanAZ** 2023-06-18 12:37 UTC
Labels: bug, help wanted, unconfirmed
